import type { ArrayEncoding } from '../encode/script.js';
import { decodeScript, scriptHashFromCbor } from '../encode/decode.js';
import { fromHex, toHex } from '../encode/cbor.js';
import { blake2b224 } from '../encode/script.js';
import { shapeOf, type ScriptShape } from '../model/invariants.js';
import type { Vector } from '../vectors/schema.js';
import type { ChainEvidenceEntry, ChainEvidenceNetwork, ChainEvidenceRecord } from './evidence.js';
import { nativeScriptsIn, referenceScriptIn, type ScriptLocation } from './scripts.js';

/**
 * The native scripts a real node has actually carried, extracted from the
 * transaction bytes in `chain-evidence/observations.json`.
 *
 * Every other byte string this project tests its decoder against was produced
 * by this project: `vectors/` is generated by `src/generate/`, and the
 * hand-built strings in `test/unit/slot-range.test.ts` were written to state a
 * rule. That is circular in the one direction that matters, because a decoder
 * and an encoder that share an author agree about framing whether or not the
 * framing is right. These bytes were framed by something else, accepted by a
 * node, and are reproduced here exactly as they arrived.
 *
 * This file is derived, not authored, and that is deliberate. Deriving it from
 * `observations.json` keeps the line this project's value rests on: the bytes
 * are observed, the extraction is a program anyone can rerun, and
 * `npm run chain-evidence:scripts:check` fails if the committed file and the
 * observations disagree. Nothing here is transcribed, so nothing here can be
 * quietly edited into saying something a node never did.
 *
 * Deduplicated by bytes rather than listed per transaction: four submissions
 * carried the same 3-of-5 DRep board and three carried the same 2-of-3 trustee
 * credential, so a per-transaction listing would test the same byte string
 * seven times and hide how few distinct scripts there really are. `carriedBy`
 * keeps the provenance a reader needs to check any of them.
 */
export const OBSERVED_SCRIPTS_FORMAT_VERSION = 1;

export const DEFAULT_OBSERVED_SCRIPTS_PATH = 'chain-evidence/scripts.json';

/** One submission that carried a script, and where in it the bytes sat. */
export interface ObservedScriptCarrier {
  network: ChainEvidenceNetwork;
  txHash: string;
  location: ScriptLocation;
}

export interface ObservedScriptRecord {
  /** blake2b-224 of the bytes below, taken as received. This is the file's key. */
  scriptHash: string;
  /** The script's CBOR exactly as a transaction carried it, lowercase hex. */
  cborHex: string;
  scriptBytes: number;
  /**
   * Which of the two standard encoders reproduce these bytes from the script
   * they decode to, as `decodeScript` reports it. An empty array means neither
   * does, so re-encoding this script would change its hash.
   *
   * Absent, rather than empty, when `decodable` is false: a script that never
   * became an AST cannot be re-encoded from one, so the question has no answer
   * instead of the answer "neither".
   */
  framings?: ArrayEncoding[];
  /**
   * False when this library cannot turn these bytes into an AST at all. A node
   * accepted them regardless, which is the finding: `scriptHashFromCbor` is
   * the primitive that still works, because hashing never decodes.
   */
  decodable: boolean;
  /** Why not, when `decodable` is false. */
  decodeError?: string;
  /** Derived from the decoded script, so absent exactly when `decodable` is false. */
  shape?: ScriptShape;
  /** The corpus vector with byte-identical CBOR, when the corpus generates this script. */
  vectorId?: string;
  carriedBy: ObservedScriptCarrier[];
}

export interface ObservedScriptsFile {
  formatVersion: number;
  scriptCount: number;
  /**
   * Digest over the script hashes this set holds, so a compat result can name
   * the set it ran against the way it already names `vectors/index.json`'s.
   * A script hash is taken over the bytes, so two sets with the same digest
   * hold the same bytes.
   */
  digest: string;
  scripts: ObservedScriptRecord[];
}

/** Digest over script hashes, mirroring `corpusDigest` in `src/vectors/build.ts`. */
export function observedScriptsDigest(scripts: readonly ObservedScriptRecord[]): string {
  const material = scripts
    .map((s) => s.scriptHash)
    .sort()
    .join('\n');
  return toHex(blake2b224(new TextEncoder().encode(material)));
}

/**
 * Every script an entry's bytes hold: the ones its own transaction carried,
 * inline or published into an output, plus the one it spent against by
 * reference, which lives in the creating transaction instead.
 */
function scriptsOf(entry: ChainEvidenceEntry): { cborHex: string; location: ScriptLocation }[] {
  const found = entry.cborHex ? nativeScriptsIn(fromHex(entry.cborHex)) : [];

  const reference = entry.referenceScript;
  if (reference) {
    const cborHex = referenceScriptIn(fromHex(reference.cborHex), reference.outputIndex);
    if (cborHex) found.push({ cborHex, location: 'reference' });
  }

  return found;
}

/** Maps a vector's two encodings back to its id, so an observed byte string can be recognized as a generated one. */
function vectorIdsByCbor(vectors: Vector[]): Map<string, string> {
  const byCbor = new Map<string, string>();
  for (const vector of vectors) {
    byCbor.set(vector.encoding.definite.cborHex, vector.id);
    byCbor.set(vector.encoding.cardanoBinary.cborHex, vector.id);
  }
  return byCbor;
}

/**
 * Builds the observed script set from the evidence record.
 *
 * Sorted by script hash and deduplicated by bytes, so regenerating twice from
 * an unchanged record produces byte-identical output and the `--check` mode is
 * meaningful. Nothing is read from the clock or the network.
 */
export function deriveObservedScripts(
  record: ChainEvidenceRecord,
  vectors: Vector[] = [],
): ObservedScriptsFile {
  const byCbor = vectorIdsByCbor(vectors);
  const scripts = new Map<string, ObservedScriptRecord>();

  for (const entry of record.entries) {
    // Provenance is the point, so a script with no transaction hash to cite is
    // not recorded at all. Only an accepted entry carries bytes, and only an
    // accepted entry has a hash, so this skips nothing the record holds today.
    const txHash = entry.txHash;
    if (!txHash) continue;

    for (const { cborHex, location } of scriptsOf(entry)) {
      const carrier: ObservedScriptCarrier = { network: entry.network, txHash, location };

      const existing = scripts.get(cborHex);
      if (existing) {
        existing.carriedBy.push(carrier);
        continue;
      }

      // Decoded for what can be said about the script, but hashed from the
      // bytes as received: re-encoding could change the framing and so the
      // hash, which is the whole reason this holds raw bytes at all.
      let decoded: ReturnType<typeof decodeScript> | undefined;
      let decodeError: string | undefined;
      try {
        decoded = decodeScript(cborHex);
      } catch (error) {
        decodeError = (error as Error).message;
      }

      scripts.set(cborHex, {
        scriptHash: scriptHashFromCbor(cborHex),
        cborHex,
        scriptBytes: cborHex.length / 2,
        decodable: decoded !== undefined,
        ...(decoded
          ? { framings: [...decoded.framings], shape: shapeOf(decoded.script) }
          : { decodeError: decodeError ?? 'decoding failed with no message' }),
        ...(byCbor.has(cborHex) ? { vectorId: byCbor.get(cborHex)! } : {}),
        carriedBy: [carrier],
      });
    }
  }

  const ordered = [...scripts.values()].sort((a, b) => a.scriptHash.localeCompare(b.scriptHash));
  for (const script of ordered) {
    script.carriedBy.sort(
      (a, b) => a.txHash.localeCompare(b.txHash) || a.location.localeCompare(b.location),
    );
  }

  return {
    formatVersion: OBSERVED_SCRIPTS_FORMAT_VERSION,
    scriptCount: ordered.length,
    digest: observedScriptsDigest(ordered),
    scripts: ordered,
  };
}

/** Serializes the derived set the way the committed file is written: two-space JSON with a trailing newline. */
export function serializeObservedScripts(file: ObservedScriptsFile): string {
  return `${JSON.stringify(file, null, 2)}\n`;
}
